"""initial schema

Revision ID: 4940e5d7dc14
Revises:
Create Date: 2026-06-13 21:20:29.858240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4940e5d7dc14"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("body_fat_pct", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("waist_cm", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_body_metrics_date"), "body_metrics", ["date"], unique=True)
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "equipment",
            sa.Enum(
                "bodyweight",
                "dumbbell",
                "pull_up_bar",
                name="equipment",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "pattern",
            sa.Enum(
                "horizontal_push",
                "vertical_push",
                "horizontal_pull",
                "vertical_pull",
                "squat",
                "hinge",
                "core",
                "conditioning",
                name="movementpattern",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("primary_muscles", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "secondary_muscles", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "level",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="level", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("is_compound", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("instructions", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_category"), "exercises", ["category"], unique=False)
    op.create_index(op.f("ix_exercises_equipment"), "exercises", ["equipment"], unique=False)
    op.create_index("ix_exercises_pattern", "exercises", ["pattern"], unique=False)
    op.create_index(op.f("ix_exercises_slug"), "exercises", ["slug"], unique=True)
    op.create_table(
        "nutrition_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("tdee_kcal", sa.Integer(), nullable=False),
        sa.Column("target_kcal", sa.Integer(), nullable=False),
        sa.Column("protein_g", sa.Integer(), nullable=False),
        sa.Column("carbs_g", sa.Integer(), nullable=False),
        sa.Column("fat_g", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nutrition_targets_date"), "nutrition_targets", ["date"], unique=False)
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "goal", sa.Enum("shred", name="goal", native_enum=False, length=32), nullable=False
        ),
        sa.Column("days_per_week", sa.Integer(), nullable=False),
        sa.Column(
            "experience_level",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="level", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("days_per_week >= 3 AND days_per_week <= 5", name="ck_plans_days"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "sex",
            sa.Enum("male", "female", name="sex", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column(
            "activity_level",
            sa.Enum(
                "sedentary",
                "light",
                "moderate",
                "active",
                "very_active",
                name="activitylevel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="level", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("age >= 14 AND age <= 100", name="ck_user_profile_age"),
        sa.CheckConstraint("id = 1", name="ck_user_profile_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plan_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("day_index", sa.Integer(), nullable=False),
        sa.Column(
            "focus",
            sa.Enum(
                "full_body",
                "upper",
                "lower",
                "push",
                "pull",
                "legs",
                "conditioning",
                name="focus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "day_index", name="uq_plan_days_plan_day"),
    )
    op.create_index(op.f("ix_plan_days_plan_id"), "plan_days", ["plan_id"], unique=False)
    op.create_table(
        "plan_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_day_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("target_reps_min", sa.Integer(), nullable=False),
        sa.Column("target_reps_max", sa.Integer(), nullable=False),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("is_conditioning", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["plan_day_id"], ["plan_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_exercises_plan_day_id"), "plan_exercises", ["plan_day_id"], unique=False
    )
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_day_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_day_id"],
            ["plan_days.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_sessions_date"), "workout_sessions", ["date"], unique=False)
    op.create_table(
        "set_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["session_id"], ["workout_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_set_logs_session_id"), "set_logs", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_set_logs_session_id"), table_name="set_logs")
    op.drop_table("set_logs")
    op.drop_index(op.f("ix_workout_sessions_date"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index(op.f("ix_plan_exercises_plan_day_id"), table_name="plan_exercises")
    op.drop_table("plan_exercises")
    op.drop_index(op.f("ix_plan_days_plan_id"), table_name="plan_days")
    op.drop_table("plan_days")
    op.drop_table("user_profile")
    op.drop_table("plans")
    op.drop_index(op.f("ix_nutrition_targets_date"), table_name="nutrition_targets")
    op.drop_table("nutrition_targets")
    op.drop_index(op.f("ix_exercises_slug"), table_name="exercises")
    op.drop_index("ix_exercises_pattern", table_name="exercises")
    op.drop_index(op.f("ix_exercises_equipment"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_category"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_body_metrics_date"), table_name="body_metrics")
    op.drop_table("body_metrics")
    # ### end Alembic commands ###
