"""add exercises.bodyweight_load_factor

Revision ID: 7217d574bf8e
Revises: afbc44da0281
Create Date: 2026-06-14 10:04:14.285321

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7217d574bf8e"
down_revision: str | None = "afbc44da0281"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column("bodyweight_load_factor", sa.Float(), server_default="1.0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "bodyweight_load_factor")
    # ### end Alembic commands ###
