"""add plans.mesocycle_week

Revision ID: afbc44da0281
Revises: 4940e5d7dc14
Create Date: 2026-06-14 09:50:42.143292

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afbc44da0281"
down_revision: str | None = "4940e5d7dc14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans", sa.Column("mesocycle_week", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "mesocycle_week")
    # ### end Alembic commands ###
