/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate Plan */
        patch: operations["activate_plan_api_plans__plan_id__activate_patch"];
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Set */
        post: operations["add_set_api_sessions__session_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Complete Session */
        patch: operations["complete_session_api_sessions__session_id__complete_patch"];
        trace?: never;
    };
    "/api/progress/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volume */
        get: operations["volume_api_progress_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/body-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Body Metrics */
        get: operations["list_body_metrics_api_body_metrics_get"];
        put?: never;
        /** Create Body Metric */
        post: operations["create_body_metric_api_body_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Targets */
        get: operations["get_targets_api_nutrition_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_api_nutrition_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityLevel
         * @enum {string}
         */
        ActivityLevel: "sedentary" | "light" | "moderate" | "active" | "very_active";
        /** BodyMetricIn */
        BodyMetricIn: {
            /** Date */
            date?: string | null;
            /** Weight Kg */
            weight_kg: number | string;
            /** Body Fat Pct */
            body_fat_pct?: number | string | null;
            /** Waist Cm */
            waist_cm?: number | string | null;
        };
        /** BodyMetricOut */
        BodyMetricOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: string;
            /** Body Fat Pct */
            body_fat_pct: string | null;
            /** Waist Cm */
            waist_cm: string | null;
        };
        /**
         * Equipment
         * @enum {string}
         */
        Equipment: "bodyweight" | "dumbbell" | "pull_up_bar";
        /** ExerciseOut */
        ExerciseOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            equipment: components["schemas"]["Equipment"];
            pattern: components["schemas"]["MovementPattern"] | null;
            /** Category */
            category: string | null;
            /** Primary Muscles */
            primary_muscles: string[];
            /** Secondary Muscles */
            secondary_muscles: string[];
            level: components["schemas"]["Level"] | null;
            /** Is Compound */
            is_compound: boolean;
            /** Instructions */
            instructions: string[];
        };
        /**
         * Focus
         * @enum {string}
         */
        Focus: "full_body" | "upper" | "lower" | "push" | "pull" | "legs" | "conditioning";
        /**
         * Goal
         * @enum {string}
         */
        Goal: "shred";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Level
         * @enum {string}
         */
        Level: "beginner" | "intermediate" | "advanced";
        /**
         * MovementPattern
         * @description Used by the generator for balanced selection (SPEC §4).
         * @enum {string}
         */
        MovementPattern: "horizontal_push" | "vertical_push" | "horizontal_pull" | "vertical_pull" | "squat" | "hinge" | "core" | "conditioning";
        /** NutritionTargetOut */
        NutritionTargetOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Tdee Kcal */
            tdee_kcal: number;
            /** Target Kcal */
            target_kcal: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
        };
        /** PlanCreateIn */
        PlanCreateIn: {
            /** @default shred */
            goal: components["schemas"]["Goal"];
            /** Days Per Week */
            days_per_week: number;
        };
        /** PlanDayOut */
        PlanDayOut: {
            /** Id */
            id: number;
            /** Day Index */
            day_index: number;
            focus: components["schemas"]["Focus"];
            /** Exercises */
            exercises: components["schemas"]["PlanExerciseOut"][];
        };
        /** PlanDetailOut */
        PlanDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            goal: components["schemas"]["Goal"];
            /** Days Per Week */
            days_per_week: number;
            experience_level: components["schemas"]["Level"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days */
            days: components["schemas"]["PlanDayOut"][];
        };
        /** PlanExerciseOut */
        PlanExerciseOut: {
            /** Id */
            id: number;
            /** Exercise Id */
            exercise_id: number;
            /** Order Index */
            order_index: number;
            /** Sets */
            sets: number;
            /** Target Reps Min */
            target_reps_min: number;
            /** Target Reps Max */
            target_reps_max: number;
            /** Rest Seconds */
            rest_seconds: number;
            /** Is Conditioning */
            is_conditioning: boolean;
            exercise: components["schemas"]["ExerciseOut"];
        };
        /** PlanSummaryOut */
        PlanSummaryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            goal: components["schemas"]["Goal"];
            /** Days Per Week */
            days_per_week: number;
            experience_level: components["schemas"]["Level"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfileIn */
        ProfileIn: {
            sex: components["schemas"]["Sex"];
            /** Age */
            age: number;
            /** Height Cm */
            height_cm: number | string;
            /** Weight Kg */
            weight_kg: number | string;
            activity_level: components["schemas"]["ActivityLevel"];
            experience_level: components["schemas"]["Level"];
        };
        /** ProfileOut */
        ProfileOut: {
            /** Id */
            id: number;
            sex: components["schemas"]["Sex"];
            /** Age */
            age: number;
            /** Height Cm */
            height_cm: string;
            /** Weight Kg */
            weight_kg: string;
            activity_level: components["schemas"]["ActivityLevel"];
            experience_level: components["schemas"]["Level"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionCreateIn */
        SessionCreateIn: {
            /** Plan Day Id */
            plan_day_id: number;
            /** Date */
            date?: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Plan Day Id */
            plan_day_id: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Notes */
            notes: string | null;
            /** Completed */
            completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Set Logs
             * @default []
             */
            set_logs: components["schemas"]["SetLogOut"][];
            /**
             * Suggested Targets
             * @default []
             */
            suggested_targets: components["schemas"]["SuggestedTargetOut"][];
        };
        /** SetLogIn */
        SetLogIn: {
            /** Exercise Id */
            exercise_id: number;
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg?: number | string | null;
            /** Rpe */
            rpe?: number | string | null;
        };
        /** SetLogOut */
        SetLogOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Exercise Id */
            exercise_id: number;
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg: string | null;
            /** Rpe */
            rpe: string | null;
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female";
        /** SuggestedTargetOut */
        SuggestedTargetOut: {
            /** Exercise Id */
            exercise_id: number;
            /** Sets */
            sets: number;
            /** Reps Min */
            reps_min: number;
            /** Reps Max */
            reps_max: number;
            /** Suggested Weight Kg */
            suggested_weight_kg: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumePoint */
        VolumePoint: {
            /** Week */
            week: string;
            /** Muscle */
            muscle: string;
            /** Volume */
            volume: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: {
                equipment?: components["schemas"]["Equipment"] | null;
                muscle?: string | null;
                category?: string | null;
                pattern?: components["schemas"]["MovementPattern"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    put_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryOut"][];
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_plan_api_plans__plan_id__activate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_set_api_sessions__session_id__sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_sessions__session_id__complete_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_api_progress_volume_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_body_metrics_api_body_metrics_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetricOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_body_metric_api_body_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyMetricIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetricOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_targets_api_nutrition_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTargetOut"];
                };
            };
        };
    };
    recompute_api_nutrition_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTargetOut"];
                };
            };
        };
    };
}
