/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Local semantic-ish exercise search (SPEC §17.3 A3).
         */
        get: operations["search_api_exercises_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise History */
        get: operations["get_exercise_history_api_exercises__exercise_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Exercise Preference */
        put: operations["put_exercise_preference_api_exercises__exercise_id__preference_put"];
        post?: never;
        /** Delete Exercise Preference */
        delete: operations["delete_exercise_preference_api_exercises__exercise_id__preference_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_profile_put"];
        /** Create Profile */
        post: operations["create_profile_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_profile_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{profile_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate Profile */
        patch: operations["activate_profile_api_profile__profile_id__activate_patch"];
        trace?: never;
    };
    "/api/profile/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_profile__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Coverage */
        get: operations["plan_coverage_api_plans__plan_id__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/fatigue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Fatigue */
        get: operations["plan_fatigue_api_plans__plan_id__fatigue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate Plan */
        patch: operations["activate_plan_api_plans__plan_id__activate_patch"];
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Set */
        post: operations["add_set_api_sessions__session_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Complete Session */
        patch: operations["complete_session_api_sessions__session_id__complete_patch"];
        trace?: never;
    };
    "/api/progress/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volume */
        get: operations["volume_api_progress_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/strength": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strength */
        get: operations["strength_api_progress_strength_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prediction
         * @description Per-exercise next-session load / readiness forecast (SPEC §17.3 A2).
         */
        get: operations["prediction_api_progress_prediction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Photos
         * @description List progress photos, newest first (SPEC §19.8 W3).
         */
        get: operations["list_photos_api_progress_photos_get"];
        put?: never;
        /** Upload Photo */
        post: operations["upload_photo_api_progress_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/photos/{photo_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo Image */
        get: operations["photo_image_api_progress_photos__photo_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["delete_photo_api_progress_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/body-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Body Metrics */
        get: operations["list_body_metrics_api_body_metrics_get"];
        put?: never;
        /** Create Body Metric */
        post: operations["create_body_metric_api_body_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Types */
        get: operations["list_types_api_measurements_types_get"];
        put?: never;
        /** Create Type */
        post: operations["create_type_api_measurements_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/types/{type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Type */
        delete: operations["delete_type_api_measurements_types__type_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_measurements_entries_get"];
        put?: never;
        /** Upsert Entry */
        post: operations["upsert_entry_api_measurements_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_measurements_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series */
        get: operations["series_api_measurements_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Targets */
        get: operations["get_targets_api_nutrition_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_api_nutrition_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Food Log */
        get: operations["get_food_log_api_nutrition_log_get"];
        put?: never;
        /** Post Food Log */
        post: operations["post_food_log_api_nutrition_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Foods */
        get: operations["recent_foods_api_nutrition_log_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log/copy-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy Food Log Day */
        post: operations["copy_food_log_day_api_nutrition_log_copy_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Food Log History */
        get: operations["food_log_history_api_nutrition_log_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/log/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Food Log */
        delete: operations["delete_food_log_api_nutrition_log__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/adaptive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Adaptive
         * @description Adaptive TDEE preview from the bodyweight trend (SPEC §17.3 A1).
         */
        get: operations["adaptive_api_nutrition_adaptive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/food/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Food Search Endpoint
         * @description Search foods by name via Open Food Facts (cached locally; SPEC §19.8 W2, opt-in/external).
         */
        get: operations["food_search_endpoint_api_nutrition_food_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/barcode/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Barcode
         * @description Look up a barcode's macros from Open Food Facts (SPEC §17.5 B2b, opt-in/external).
         */
        get: operations["barcode_api_nutrition_barcode__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/adaptive/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Adaptive
         * @description Persist today's targets from the adaptive TDEE estimate (SPEC §17.3 A1).
         */
        post: operations["apply_adaptive_api_nutrition_adaptive_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityLevel
         * @enum {string}
         */
        ActivityLevel: "sedentary" | "light" | "moderate" | "active" | "very_active";
        /**
         * AdaptiveTDEEOut
         * @description Adaptive TDEE preview (SPEC §17.3 A1). When `enough_data` is false the estimate
         *     fields are null and `reason` explains why.
         */
        AdaptiveTDEEOut: {
            /** Enough Data */
            enough_data: boolean;
            /**
             * Samples
             * @default 0
             */
            samples: number;
            /**
             * Days Span
             * @default 0
             */
            days_span: number;
            /** Reason */
            reason?: string | null;
            /** Static Tdee Kcal */
            static_tdee_kcal?: number | null;
            /** Estimated Tdee Kcal */
            estimated_tdee_kcal?: number | null;
            /** Assumed Intake Kcal */
            assumed_intake_kcal?: number | null;
            /** Weight Change Kg Per Week */
            weight_change_kg_per_week?: number | null;
            /**
             * Clamped
             * @default false
             */
            clamped: boolean;
            suggested?: components["schemas"]["SuggestedTargets"] | null;
        };
        /** BodyMetricIn */
        BodyMetricIn: {
            /** Date */
            date?: string | null;
            /** Weight Kg */
            weight_kg: number | string;
            /** Body Fat Pct */
            body_fat_pct?: number | string | null;
            /** Waist Cm */
            waist_cm?: number | string | null;
        };
        /** BodyMetricOut */
        BodyMetricOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: string;
            /** Body Fat Pct */
            body_fat_pct: string | null;
            /** Waist Cm */
            waist_cm: string | null;
        };
        /** Body_upload_photo_api_progress_photos_post */
        Body_upload_photo_api_progress_photos_post: {
            /** File */
            file: string;
            /** Date */
            date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** CoveragePointOut */
        CoveragePointOut: {
            /** Muscle */
            muscle: string;
            /** Sets */
            sets: number;
            /** Target */
            target: number;
            /** Met */
            met: boolean;
        };
        /** DailyFoodLogOut */
        DailyFoodLogOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Entries */
            entries: components["schemas"]["FoodLogOut"][];
            totals: components["schemas"]["FoodLogTotalsOut"];
            target: components["schemas"]["NutritionTargetOut"] | null;
            /** Remaining Kcal */
            remaining_kcal: number | null;
            /** Remaining Protein G */
            remaining_protein_g: string | null;
            /** Remaining Carbs G */
            remaining_carbs_g: string | null;
            /** Remaining Fat G */
            remaining_fat_g: string | null;
        };
        /** DayFatigueOut */
        DayFatigueOut: {
            /** Day Index */
            day_index: number;
            focus: components["schemas"]["Focus"];
            /** Fatigue */
            fatigue: number;
        };
        /**
         * Equipment
         * @enum {string}
         */
        Equipment: "bodyweight" | "dumbbell" | "pull_up_bar";
        /** ExerciseHistoryOut */
        ExerciseHistoryOut: {
            /** Exercise Id */
            exercise_id: number;
            /** Sessions */
            sessions: components["schemas"]["HistorySessionOut"][];
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            equipment: components["schemas"]["Equipment"];
            pattern: components["schemas"]["MovementPattern"] | null;
            /** Category */
            category: string | null;
            /** Primary Muscles */
            primary_muscles: string[];
            /** Secondary Muscles */
            secondary_muscles: string[];
            level: components["schemas"]["Level"] | null;
            /** Is Compound */
            is_compound: boolean;
            /** Instructions */
            instructions: string[];
            preference?: components["schemas"]["ExercisePreferenceStatus"] | null;
        };
        /** ExercisePreferenceIn */
        ExercisePreferenceIn: {
            status: components["schemas"]["ExercisePreferenceStatus"];
        };
        /** ExercisePreferenceOut */
        ExercisePreferenceOut: {
            /** Exercise Id */
            exercise_id: number;
            status: components["schemas"]["ExercisePreferenceStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExercisePreferenceStatus
         * @enum {string}
         */
        ExercisePreferenceStatus: "favorite" | "avoid";
        /** ExerciseSearchHitOut */
        ExerciseSearchHitOut: {
            /** Score */
            score: number;
            exercise: components["schemas"]["ExerciseOut"];
        };
        /** ExerciseStrengthOut */
        ExerciseStrengthOut: {
            /** Exercise Id */
            exercise_id: number;
            /** Exercise Name */
            exercise_name: string;
            pattern: components["schemas"]["MovementPattern"] | null;
            /** Weighted */
            weighted: boolean;
            /** Best E1Rm */
            best_e1rm: number | null;
            /** Best Weight */
            best_weight: number | null;
            /** Best Reps */
            best_reps: number;
            /** Latest Is Pr */
            latest_is_pr: boolean;
            /** Points */
            points: components["schemas"]["StrengthPointOut"][];
        };
        /**
         * Focus
         * @enum {string}
         */
        Focus: "full_body" | "upper" | "lower" | "push" | "pull" | "legs" | "conditioning";
        /**
         * FoodFactsOut
         * @description Macros for a scanned barcode, per 100 g (SPEC §17.5 B2b).
         */
        FoodFactsOut: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Brand */
            brand: string | null;
            /** Serving Size */
            serving_size: string | null;
            /** Kcal Per 100G */
            kcal_per_100g: number | null;
            /** Protein Per 100G */
            protein_per_100g: number | null;
            /** Carbs Per 100G */
            carbs_per_100g: number | null;
            /** Fat Per 100G */
            fat_per_100g: number | null;
        };
        /** FoodLogCopyDayIn */
        FoodLogCopyDayIn: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
        };
        /** FoodLogIn */
        FoodLogIn: {
            /** Date */
            date?: string | null;
            /** Name */
            name: string;
            /** Grams */
            grams: number | string;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number | string;
            /** Carbs G */
            carbs_g: number | string;
            /** Fat G */
            fat_g: number | string;
            /** @default manual */
            source: components["schemas"]["FoodLogSource"];
            /** Barcode */
            barcode?: string | null;
        };
        /** FoodLogOut */
        FoodLogOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Name */
            name: string;
            /** Grams */
            grams: string;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: string;
            /** Carbs G */
            carbs_g: string;
            /** Fat G */
            fat_g: string;
            source: components["schemas"]["FoodLogSource"];
            /** Barcode */
            barcode: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FoodLogRecentOut */
        FoodLogRecentOut: {
            /** Name */
            name: string;
            /** Grams */
            grams: string;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: string;
            /** Carbs G */
            carbs_g: string;
            /** Fat G */
            fat_g: string;
            source: components["schemas"]["FoodLogSource"];
            /** Barcode */
            barcode: string | null;
            /**
             * Last Logged On
             * Format: date
             */
            last_logged_on: string;
        };
        /**
         * FoodLogSource
         * @enum {string}
         */
        FoodLogSource: "manual" | "barcode" | "llm";
        /** FoodLogTotalsOut */
        FoodLogTotalsOut: {
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: string;
            /** Carbs G */
            carbs_g: string;
            /** Fat G */
            fat_g: string;
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "shred";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistorySessionOut */
        HistorySessionOut: {
            /** Session Id */
            session_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sets */
            sets: components["schemas"]["HistorySetOut"][];
        };
        /** HistorySetOut */
        HistorySetOut: {
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg: string | null;
            /** Rpe */
            rpe: string | null;
        };
        /**
         * Level
         * @enum {string}
         */
        Level: "beginner" | "intermediate" | "advanced";
        /** LoadPredictionOut */
        LoadPredictionOut: {
            /** Exercise Id */
            exercise_id: number;
            /** Exercise Name */
            exercise_name: string;
            /** Weighted */
            weighted: boolean;
            /** Sessions */
            sessions: number;
            /** Current */
            current: number | null;
            /** Predicted Next */
            predicted_next: number | null;
            /** Trend Per Session */
            trend_per_session: number | null;
            /** Avg Recent Rpe */
            avg_recent_rpe: number | null;
            /** Readiness */
            readiness: string;
            /** Confidence */
            confidence: number;
        };
        /** MeasurementEntryIn */
        MeasurementEntryIn: {
            /** Type Id */
            type_id: number;
            /** Date */
            date?: string | null;
            /** Value */
            value: number | string;
        };
        /** MeasurementEntryOut */
        MeasurementEntryOut: {
            /** Id */
            id: number;
            /** Type Id */
            type_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: string;
        };
        /**
         * MeasurementSeriesOut
         * @description One measurement type plus its chronological points (for /progress charts).
         */
        MeasurementSeriesOut: {
            type: components["schemas"]["MeasurementTypeOut"];
            /** Points */
            points: components["schemas"]["MeasurementSeriesPointOut"][];
            /** Latest */
            latest: string | null;
            /** Change */
            change: string | null;
        };
        /** MeasurementSeriesPointOut */
        MeasurementSeriesPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: string;
        };
        /** MeasurementTypeIn */
        MeasurementTypeIn: {
            /** Label */
            label: string;
            /**
             * Unit
             * @default cm
             */
            unit: string;
        };
        /** MeasurementTypeOut */
        MeasurementTypeOut: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Builtin */
            builtin: boolean;
        };
        /**
         * MovementPattern
         * @description Used by the generator for balanced selection (SPEC §4).
         * @enum {string}
         */
        MovementPattern: "horizontal_push" | "vertical_push" | "horizontal_pull" | "vertical_pull" | "squat" | "hinge" | "core" | "conditioning";
        /** NutritionHistoryDayOut */
        NutritionHistoryDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Logged */
            logged: boolean;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: string;
            /** Carbs G */
            carbs_g: string;
            /** Fat G */
            fat_g: string;
            /** Target Kcal */
            target_kcal: number | null;
            /** Target Protein G */
            target_protein_g: number | null;
            /** Target Carbs G */
            target_carbs_g: number | null;
            /** Target Fat G */
            target_fat_g: number | null;
            /** Kcal Adherent */
            kcal_adherent: boolean;
        };
        /** NutritionHistoryOut */
        NutritionHistoryOut: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Days */
            days: components["schemas"]["NutritionHistoryDayOut"][];
            /** Logged Days */
            logged_days: number;
            /** Target Days */
            target_days: number;
            /** Adherent Days */
            adherent_days: number;
            /** Adherence Pct */
            adherence_pct: number;
        };
        /** NutritionTargetOut */
        NutritionTargetOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Tdee Kcal */
            tdee_kcal: number;
            /** Target Kcal */
            target_kcal: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
        };
        /** PlanCreateIn */
        PlanCreateIn: {
            /** @default shred */
            goal: components["schemas"]["Goal"];
            /** Days Per Week */
            days_per_week: number;
            /**
             * Week
             * @default 1
             */
            week: number;
        };
        /** PlanDayOut */
        PlanDayOut: {
            /** Id */
            id: number;
            /** Day Index */
            day_index: number;
            focus: components["schemas"]["Focus"];
            /** Exercises */
            exercises: components["schemas"]["PlanExerciseOut"][];
        };
        /** PlanDetailOut */
        PlanDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            goal: components["schemas"]["Goal"];
            /** Days Per Week */
            days_per_week: number;
            experience_level: components["schemas"]["Level"];
            /** Mesocycle Week */
            mesocycle_week: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days */
            days: components["schemas"]["PlanDayOut"][];
        };
        /** PlanExerciseOut */
        PlanExerciseOut: {
            /** Id */
            id: number;
            /** Exercise Id */
            exercise_id: number;
            /** Order Index */
            order_index: number;
            /** Sets */
            sets: number;
            /** Target Reps Min */
            target_reps_min: number;
            /** Target Reps Max */
            target_reps_max: number;
            /** Rest Seconds */
            rest_seconds: number;
            /** Is Conditioning */
            is_conditioning: boolean;
            exercise: components["schemas"]["ExerciseOut"];
        };
        /** PlanSummaryOut */
        PlanSummaryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            goal: components["schemas"]["Goal"];
            /** Days Per Week */
            days_per_week: number;
            experience_level: components["schemas"]["Level"];
            /** Mesocycle Week */
            mesocycle_week: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfileIn */
        ProfileIn: {
            /** Name */
            name?: string | null;
            sex: components["schemas"]["Sex"];
            /** Age */
            age: number;
            /** Height Cm */
            height_cm: number | string;
            /** Weight Kg */
            weight_kg: number | string;
            activity_level: components["schemas"]["ActivityLevel"];
            experience_level: components["schemas"]["Level"];
            /** Limitations */
            limitations?: ("shoulder" | "knee" | "lower_back" | "wrist" | "pull_up")[];
        };
        /** ProfileOut */
        ProfileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
            sex: components["schemas"]["Sex"];
            /** Age */
            age: number;
            /** Height Cm */
            height_cm: string;
            /** Weight Kg */
            weight_kg: string;
            activity_level: components["schemas"]["ActivityLevel"];
            experience_level: components["schemas"]["Level"];
            /** Limitations */
            limitations: ("shoulder" | "knee" | "lower_back" | "wrist" | "pull_up")[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProgressPhotoOut */
        ProgressPhotoOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Note */
            note: string | null;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Image Url */
            image_url: string;
        };
        /** SessionCompleteIn */
        SessionCompleteIn: {
            /** Notes */
            notes?: string | null;
        };
        /** SessionCreateIn */
        SessionCreateIn: {
            /** Plan Day Id */
            plan_day_id: number;
            /** Date */
            date?: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Plan Day Id */
            plan_day_id: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Notes */
            notes: string | null;
            /** Completed */
            completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Set Logs
             * @default []
             */
            set_logs: components["schemas"]["SetLogOut"][];
            /**
             * Suggested Targets
             * @default []
             */
            suggested_targets: components["schemas"]["SuggestedTargetOut"][];
        };
        /** SetLogIn */
        SetLogIn: {
            /** Exercise Id */
            exercise_id: number;
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg?: number | string | null;
            /** Rpe */
            rpe?: number | string | null;
        };
        /** SetLogOut */
        SetLogOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Exercise Id */
            exercise_id: number;
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg: string | null;
            /** Rpe */
            rpe: string | null;
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female";
        /** StrengthPointOut */
        StrengthPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** E1Rm */
            e1rm: number | null;
            /** Top Weight */
            top_weight: number | null;
            /** Top Reps */
            top_reps: number;
        };
        /** SuggestedTargetOut */
        SuggestedTargetOut: {
            /** Exercise Id */
            exercise_id: number;
            /** Sets */
            sets: number;
            /** Reps Min */
            reps_min: number;
            /** Reps Max */
            reps_max: number;
            /** Suggested Weight Kg */
            suggested_weight_kg: number | null;
        };
        /** SuggestedTargets */
        SuggestedTargets: {
            /** Target Kcal */
            target_kcal: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumePoint */
        VolumePoint: {
            /** Week */
            week: string;
            /** Muscle */
            muscle: string;
            /** Volume */
            volume: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: {
                equipment?: components["schemas"]["Equipment"] | null;
                muscle?: string | null;
                category?: string | null;
                pattern?: components["schemas"]["MovementPattern"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_exercises_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseSearchHitOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_history_api_exercises__exercise_id__history_get: {
        parameters: {
            query?: {
                sessions?: number;
            };
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_exercise_preference_api_exercises__exercise_id__preference_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExercisePreferenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePreferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exercise_preference_api_exercises__exercise_id__preference_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    put_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profile_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
        };
    };
    activate_profile_api_profile__profile_id__activate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_profile__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryOut"][];
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_coverage_api_plans__plan_id__coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoveragePointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_fatigue_api_plans__plan_id__fatigue_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayFatigueOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_plan_api_plans__plan_id__activate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_set_api_sessions__session_id__sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_sessions__session_id__complete_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionCompleteIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_api_progress_volume_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strength_api_progress_strength_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseStrengthOut"][];
                };
            };
        };
    };
    prediction_api_progress_prediction_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadPredictionOut"][];
                };
            };
        };
    };
    list_photos_api_progress_photos_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressPhotoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_progress_photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_api_progress_photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressPhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_image_api_progress_photos__photo_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_progress_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_body_metrics_api_body_metrics_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetricOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_body_metric_api_body_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyMetricIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMetricOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_types_api_measurements_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementTypeOut"][];
                };
            };
        };
    };
    create_type_api_measurements_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementTypeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_type_api_measurements_types__type_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_measurements_entries_get: {
        parameters: {
            query?: {
                type_id?: number | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_entry_api_measurements_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementEntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_measurements_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_api_measurements_series_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementSeriesOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_targets_api_nutrition_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTargetOut"];
                };
            };
        };
    };
    recompute_api_nutrition_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTargetOut"];
                };
            };
        };
    };
    get_food_log_api_nutrition_log_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyFoodLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_food_log_api_nutrition_log_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyFoodLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_foods_api_nutrition_log_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodLogRecentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_food_log_day_api_nutrition_log_copy_day_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodLogCopyDayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyFoodLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    food_log_history_api_nutrition_log_history_get: {
        parameters: {
            query?: {
                end_date?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_food_log_api_nutrition_log__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyFoodLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adaptive_api_nutrition_adaptive_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdaptiveTDEEOut"];
                };
            };
        };
    };
    food_search_endpoint_api_nutrition_food_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodFactsOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    barcode_api_nutrition_barcode__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodFactsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_adaptive_api_nutrition_adaptive_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTargetOut"];
                };
            };
        };
    };
}
